---
- name: Create Zones
  hosts: firewalls
  gather_facts: false  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    fw:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
  
  tasks:
  - name: Create DMZ Zone
    paloaltonetworks.panos.panos_zone:
      provider: "{{ fw }}"
      zone: "dmz"
      mode: "layer3"
  
  - name: Create Private Zone
    paloaltonetworks.panos.panos_zone:
      provider: "{{ fw }}"    
      zone: "private"
      mode: "layer3"
