---
- name: Configure Admin Password
  hosts: firewalls
  gather_facts: false  
  vars:
    ansible_python_interpreter: /usr/bin/python3
  
  tasks:
  - name: Set Firewall admin password
    paloaltonetworks.panos.panos_admpwd:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      key_filename: "{{ key_filename }}"
      newpassword: "{{ password }}"
